/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BaseDatos.ConexionBase;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan Adams
 */
public class DirectorioAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContactosEst
     */
    public DirectorioAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setIconifiable(true);
        setTitle("Directorio");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Phone Number.png"))); // NOI18N

        jLabel1.setText("Buscar por");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Año", "Sección", "ID" }));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Consultar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Año", "Sección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane6.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jScrollPane6))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiantes", jPanel1);

        jLabel3.setText("Buscar por");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre","ID", "ID Estudiante"}));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Primer Apellido", "Segundo Apellido", "ID Estudiantes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
            jTable3.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane7.setViewportView(jScrollPane4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Encargados", jPanel3);

        jLabel4.setText("Buscar por");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Materia", "ID"}));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Consultar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Materias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
            jTable4.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane8.setViewportView(jScrollPane5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profesores", jPanel4);

        jLabel2.setText("Detalle");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setMaximumSize(new java.awt.Dimension(20, 20));
        jTextArea1.setMinimumSize(new java.awt.Dimension(5, 5));
        jTextArea1.setName(""); // NOI18N
        jScrollPane3.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
        String [][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo");
        String nombreColumnas[]={"ID","Nombre","Primer Apellido","Segundo Apellido","Año","Sección"};
        DefaultTableModel tableModel= new DefaultTableModel(nombreColumnas,0);
        tableModel.setRowCount(0);
        jTable1.setModel(tableModel);
        for (int i = 0; i < sql.length; i++) {
            String[][] sql2= base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo"); 
            tableModel.addRow(new Object[]{sql2[i][0],sql2[i][1],sql2[i][2],sql2[i][3],sql2[i][4],sql2[i][5]});
        }
        jTable1.setModel(tableModel);
        } else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String parametro = jComboBox1.getSelectedItem().toString();
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
            if ("Nombre".equals(parametro)) {
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and p.nombre1 = '" + jTextField1.getText() + "';");
                String nombreColumnas[] = {"ID","Nombre","Primer Apellido","Segundo Apellido","Año","Sección"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable1.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and p.nombre1 = '" + jTextField1.getText() + "';");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4], sql2[i][5]});
                }
                jTable1.setModel(tableModel);
            } else if ("Año".equals(parametro)) {
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and g.anno = '" + jTextField1.getText() + "';");
                String nombreColumnas[] = {"ID","Nombre","Primer Apellido","Segundo Apellido","Año","Sección"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable1.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and g.anno = '" + jTextField1.getText() + "';");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4], sql2[i][5]});
                }
                jTable1.setModel(tableModel);
            } else if ("Sección".equals(parametro)){
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and g.seccion = '" + jTextField1.getText() + "';");
                String nombreColumnas[] = {"ID","Nombre","Primer Apellido","Segundo Apellido","Año","Sección"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable1.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and g.seccion = '" + jTextField1.getText() + "';");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4], sql2[i][5]});
                }
                jTable1.setModel(tableModel);
            }
            else {
               String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and p.idpersona = '" + jTextField1.getText() + "';");
                String nombreColumnas[] = {"ID","Nombre","Primer Apellido","Segundo Apellido","Año","Sección"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable1.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, g.anno, g.seccion from persona p, grupo g, estudiante e where p.idpersona = e.idpersona and e.idgrupo = g.idgrupo and p.idpersona = '" + jTextField1.getText() + "';");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4], sql2[i][5]});
                }
                jTable1.setModel(tableModel); 
            }

        } else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
        String [][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
        String nombreColumnas[]={"ID", "Nombre","Primer Apellido","Segundo Apellido","ID Estudiantes"};
        DefaultTableModel tableModel= new DefaultTableModel(nombreColumnas,0);
        tableModel.setRowCount(0);
        jTable3.setModel(tableModel);
        for (int i = 0; i < sql.length; i++) {
            String[][] sql2= base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona group by p.idpersona, p.nombre1, p.apellido1, p.apellido2"); 
            tableModel.addRow(new Object[]{sql2[i][0],sql2[i][1],sql2[i][2],sql2[i][3],sql2[i][4]});
        }
        jTable3.setModel(tableModel);
        } else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String parametro = jComboBox2.getSelectedItem().toString();
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
            if ("Nombre".equals(parametro)) {
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona and p.nombre1 = '" + jTextField2.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                String nombreColumnas[] = {"ID", "Nombre","Primer Apellido","Segundo Apellido","ID Estudiantes"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable3.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona and p.nombre1 = '" + jTextField2.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4]});
                }
                jTable3.setModel(tableModel);
            } else if ("ID".equals(parametro)) {
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona and p.idpersona = '" + jTextField2.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                String nombreColumnas[] = {"ID", "Nombre","Primer Apellido","Segundo Apellido","ID Estudiantes"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable3.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona and p.idpersona = '" + jTextField2.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4]});
                }
                jTable3.setModel(tableModel);
            } else {
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona and pf.idhijo = '" + jTextField2.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                String nombreColumnas[] = {"ID", "Nombre","Primer Apellido","Segundo Apellido","ID Estudiantes"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable3.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(pf.idhijo, ', ') as Hijos from persona p, padrefamilia pf, estudiante e where p.idpersona = pf.idpersona and pf.idhijo = e.idpersona and pf.idhijo = '" + jTextField2.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4]});
                }
                jTable3.setModel(tableModel);
            }
        } else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
            String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
            String nombreColumnas[] = {"ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Materias"};
            DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
            tableModel.setRowCount(0);
            jTable4.setModel(tableModel);
            for (int i = 0; i < sql.length; i++) {
                String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4]});
            }
            jTable4.setModel(tableModel);
        } else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String parametro = jComboBox3.getSelectedItem().toString();
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
            if ("Nombre".equals(parametro)) {
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria and p.nombre1 = '" + jTextField3.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                String nombreColumnas[] = {"ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Materias"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable4.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria and p.nombre1 = '" + jTextField3.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4]});
                }
                jTable4.setModel(tableModel);
            } else if ("ID".equals(parametro)){
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria and p.idpersona = '" + jTextField3.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                String nombreColumnas[] = {"ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Materias"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable4.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria and p.idpersona = '" + jTextField3.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4]});
                }
                jTable4.setModel(tableModel);
            }
            else{
                String[][] sql = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria and m.nombremateria = '" + jTextField3.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                String nombreColumnas[] = {"ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Materias"};
                DefaultTableModel tableModel = new DefaultTableModel(nombreColumnas, 0);
                tableModel.setRowCount(0);
                jTable4.setModel(tableModel);
                for (int i = 0; i < sql.length; i++) {
                    String[][] sql2 = base.getDatosConsulta("select p.idpersona, p.nombre1, p.apellido1, p.apellido2, string_agg(m.nombremateria, ', ') as materias from persona p, materias m, profesores pr where p.idpersona = pr.idpersona and pr.idmateriaasignada = m.idmateria and m.nombremateria = '" + jTextField3.getText() + "' group by p.idpersona, p.nombre1, p.apellido1, p.apellido2");
                    tableModel.addRow(new Object[]{sql2[i][0], sql2[i][1], sql2[i][2], sql2[i][3], sql2[i][4]});
                }
                jTable4.setModel(tableModel);
            }
        } else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
        int selectedRowIndex = jTable1.getSelectedRow();
        String selectedObject = jTable1.getModel().getValueAt(selectedRowIndex, 0).toString();
        String[][] sql = base.getDatosConsulta("select concat('Dirección de ',r2.direcciones), concat('Teléfono de ',r3.telefonos), concat('Email: ',r4.email) from	(select d.idpersona, string_agg(concat(d.tipo, ': ',p.descripcion,', ' ,c.descripcion, ', ',d.descripcion),'; Dirección de  ') as Direcciones from dirpersona d, provincia p, canton c where p.idprovincia = c.idprovincia and d.idprovincia = p.idprovincia and d.idcanton = c.idcanton and d.idpersona = '"+selectedObject+"' group by d.idpersona)r2, (select idpersona, string_agg(concat(tipotelefono, ': ',numerotelefono),'; Teléfono de ') as Telefonos from telefono where idpersona = '"+selectedObject+"' group by idpersona)r3, (select idpersona, email from persona where idpersona = '"+selectedObject+"')r4 where r2.idpersona = r3.idpersona and r2.idpersona = r4.idpersona");
        jTextArea1.setText(sql[0][0]+"\n"+sql[0][1]+"\n"+sql[0][2]);
        }else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
        int selectedRowIndex = jTable3.getSelectedRow();
        String selectedObject = jTable3.getModel().getValueAt(selectedRowIndex, 0).toString();
        String[][] sql = base.getDatosConsulta("select concat('Dirección de ',r2.direcciones), concat('Teléfono de ',r3.telefonos), concat('Email: ',r4.email) from	(select d.idpersona, string_agg(concat(d.tipo, ': ',p.descripcion,', ' ,c.descripcion, ', ',d.descripcion),'; Dirección de  ') as Direcciones from dirpersona d, provincia p, canton c where p.idprovincia = c.idprovincia and d.idprovincia = p.idprovincia and d.idcanton = c.idcanton and d.idpersona = '"+selectedObject+"' group by d.idpersona)r2, (select idpersona, string_agg(concat(tipotelefono, ': ',numerotelefono),'; Teléfono de ') as Telefonos from telefono where idpersona = '"+selectedObject+"' group by idpersona)r3, (select idpersona, email from persona where idpersona = '"+selectedObject+"')r4 where r2.idpersona = r3.idpersona and r2.idpersona = r4.idpersona");
        jTextArea1.setText(sql[0][0]+"\n"+sql[0][1]+"\n"+sql[0][2]);
        }else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        ConexionBase base = new ConexionBase();
        if (base.getConexionCorrecta() != -1) {
        int selectedRowIndex = jTable4.getSelectedRow();
        String selectedObject = jTable4.getModel().getValueAt(selectedRowIndex, 0).toString();
        String[][] sql = base.getDatosConsulta("select concat('Dirección de ',r2.direcciones), concat('Teléfono de ',r3.telefonos), concat('Email: ',r4.email) from	(select d.idpersona, string_agg(concat(d.tipo, ': ',p.descripcion,', ' ,c.descripcion, ', ',d.descripcion),'; Dirección de  ') as Direcciones from dirpersona d, provincia p, canton c where p.idprovincia = c.idprovincia and d.idprovincia = p.idprovincia and d.idcanton = c.idcanton and d.idpersona = '"+selectedObject+"' group by d.idpersona)r2, (select idpersona, string_agg(concat(tipotelefono, ': ',numerotelefono),'; Teléfono de ') as Telefonos from telefono where idpersona = '"+selectedObject+"' group by idpersona)r3, (select idpersona, email from persona where idpersona = '"+selectedObject+"')r4 where r2.idpersona = r3.idpersona and r2.idpersona = r4.idpersona");
        jTextArea1.setText(sql[0][0]+"\n"+sql[0][1]+"\n"+sql[0][2]);
        }else {
            System.err.println("No se ha logrado establecer conexión con la base de datos");
        }
    }//GEN-LAST:event_jTable4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
