/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Imagenes.ImagenFondo;
import javax.swing.JOptionPane;

/**
 *
 * @author fugalde
 */
public class EscritorioProfesor extends javax.swing.JFrame {

    /**
     * Creates new form EscritorioProfesor
     */
    public EscritorioProfesor() {
        initComponents();
        escritorioProf.setBorder(new ImagenFondo());
        this.setExtendedState(EscritorioProfesor.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioProf = new javax.swing.JDesktopPane();
        menuProfesor = new javax.swing.JMenuBar();
        archivoProf = new javax.swing.JMenu();
        cmbUserProf = new javax.swing.JMenuItem();
        cerrarProf = new javax.swing.JMenuItem();
        VerProf = new javax.swing.JMenu();
        asignacionesProf = new javax.swing.JMenu();
        crearAsignacionProf = new javax.swing.JMenuItem();
        editarAsigProf = new javax.swing.JMenuItem();
        eliminarAsigAdmin = new javax.swing.JMenuItem();
        eventosProf = new javax.swing.JMenuItem();
        calificacionesProf = new javax.swing.JMenuItem();
        mensajesProf = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        busquedaProf = new javax.swing.JMenu();
        ItemDirectorio = new javax.swing.JMenuItem();
        perfilProf = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        alertaProf = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioProfLayout = new javax.swing.GroupLayout(escritorioProf);
        escritorioProf.setLayout(escritorioProfLayout);
        escritorioProfLayout.setHorizontalGroup(
            escritorioProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        escritorioProfLayout.setVerticalGroup(
            escritorioProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        menuProfesor.setAutoscrolls(true);

        archivoProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/home.png")));
        archivoProf.setText("Archivo");

        cmbUserProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/person.png")));
        cmbUserProf.setText("Cambiar de usuario");
        cmbUserProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserProfActionPerformed(evt);
            }
        });
        archivoProf.add(cmbUserProf);

        cerrarProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/turn off.png")));
        cerrarProf.setText("Cerrar");
        cerrarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarProfActionPerformed(evt);
            }
        });
        archivoProf.add(cerrarProf);

        menuProfesor.add(archivoProf);

        VerProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/table.png")));
        VerProf.setText("Ver");

        asignacionesProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clipboard.png")));
        asignacionesProf.setText("Asignaciones");

        crearAsignacionProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/list.png")));
        crearAsignacionProf.setText("Crear");
        crearAsignacionProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAsignacionProfActionPerformed(evt);
            }
        });
        asignacionesProf.add(crearAsignacionProf);

        editarAsigProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modify.png")));
        editarAsigProf.setText("Editar");
        editarAsigProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAsigProfActionPerformed(evt);
            }
        });
        asignacionesProf.add(editarAsigProf);

        eliminarAsigAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete.png")));
        eliminarAsigAdmin.setText("Eliminar");
        eliminarAsigAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAsigAdminActionPerformed(evt);
            }
        });
        asignacionesProf.add(eliminarAsigAdmin);

        VerProf.add(asignacionesProf);

        eventosProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calendar.png")));
        eventosProf.setText("Eventos");
        eventosProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosProfActionPerformed(evt);
            }
        });
        VerProf.add(eventosProf);

        calificacionesProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3d bar chart.png")));
        calificacionesProf.setText("Calificaciones");
        VerProf.add(calificacionesProf);

        menuProfesor.add(VerProf);

        mensajesProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mail.png")));
        mensajesProf.setText("Mensajes");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/People.png"))); // NOI18N
        jMenuItem1.setText("Grupo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mensajesProf.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Home.png"))); // NOI18N
        jMenuItem3.setText("Escuela");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mensajesProf.add(jMenuItem3);

        menuProfesor.add(mensajesProf);

        busquedaProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search.png")));
        busquedaProf.setText("Busqueda");

        ItemDirectorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Phone number.png"))); // NOI18N
        ItemDirectorio.setText("Directorio");
        ItemDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemDirectorioActionPerformed(evt);
            }
        });
        busquedaProf.add(ItemDirectorio);

        menuProfesor.add(busquedaProf);

        perfilProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boss.png")));
        perfilProf.setText("Perfil");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Male.png"))); // NOI18N
        jMenuItem2.setText("Datos Personales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        perfilProf.add(jMenuItem2);

        menuProfesor.add(perfilProf);

        alertaProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/warning.png")));
        alertaProf.setText("Alertas");
        menuProfesor.add(alertaProf);

        setJMenuBar(menuProfesor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioProf)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioProf)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearAsignacionProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAsignacionProfActionPerformed
        CrearAsignacion asigProf= new CrearAsignacion();
        escritorioProf.add(asigProf);
        asigProf.show();
    }//GEN-LAST:event_crearAsignacionProfActionPerformed

    private void cerrarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarProfActionPerformed
        int answ= JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir del sistema?");
        if(answ==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_cerrarProfActionPerformed

    private void cmbUserProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserProfActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmbUserProfActionPerformed

    private void editarAsigProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAsigProfActionPerformed
        EditarAsignacion editAsig= new EditarAsignacion();
        escritorioProf.add(editAsig);
        editAsig.show();
    }//GEN-LAST:event_editarAsigProfActionPerformed

    private void eliminarAsigAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAsigAdminActionPerformed
        EliminarAsignacion elimAsig = new EliminarAsignacion();
        escritorioProf.add(elimAsig);
        elimAsig.show();
    }//GEN-LAST:event_eliminarAsigAdminActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MensajesProf mnjProf= new MensajesProf();
        escritorioProf.add(mnjProf);
        mnjProf.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void eventosProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosProfActionPerformed
        VerEventos vEvento= new VerEventos();
        escritorioProf.add(vEvento);
        vEvento.show();
    }//GEN-LAST:event_eventosProfActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CrearPerfilProf perfProf= new CrearPerfilProf();
        escritorioProf.add(perfProf);
        perfProf.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MensajesEscuela mnjEsc= new MensajesEscuela();
        escritorioProf.add(mnjEsc);
        mnjEsc.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ItemDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemDirectorioActionPerformed
        DirectorioProf dProf = new DirectorioProf();
        escritorioProf.add(dProf);
        dProf.show();
    }//GEN-LAST:event_ItemDirectorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscritorioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscritorioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscritorioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscritorioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscritorioProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemDirectorio;
    private javax.swing.JMenu VerProf;
    private javax.swing.JMenu alertaProf;
    private javax.swing.JMenu archivoProf;
    private javax.swing.JMenu asignacionesProf;
    private javax.swing.JMenu busquedaProf;
    private javax.swing.JMenuItem calificacionesProf;
    private javax.swing.JMenuItem cerrarProf;
    private javax.swing.JMenuItem cmbUserProf;
    private javax.swing.JMenuItem crearAsignacionProf;
    private javax.swing.JMenuItem editarAsigProf;
    private javax.swing.JMenuItem eliminarAsigAdmin;
    private javax.swing.JDesktopPane escritorioProf;
    private javax.swing.JMenuItem eventosProf;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mensajesProf;
    private javax.swing.JMenuBar menuProfesor;
    private javax.swing.JMenu perfilProf;
    // End of variables declaration//GEN-END:variables
}
