/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Imagenes.ImagenFondo;

/**
 *
 * @author fugalde
 */
public class EscritorioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form EscritorioAdmin
     */
    public EscritorioAdmin() {
        initComponents();
        escritorioAdmin.setBorder(new ImagenFondo());
        this.setExtendedState(EscritorioProfesor.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioAdmin = new javax.swing.JDesktopPane();
        menuAdmin = new javax.swing.JMenuBar();
        archivoAdmin = new javax.swing.JMenu();
        verAdmin = new javax.swing.JMenu();
        asignacionesAdmin = new javax.swing.JMenuItem();
        eventosAdmin = new javax.swing.JMenuItem();
        calificacionesAdmin = new javax.swing.JMenuItem();
        mensajesAdmin = new javax.swing.JMenu();
        busquedaAdmin = new javax.swing.JMenu();
        perfilAdmin = new javax.swing.JMenu();
        alertasAdmin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioAdminLayout = new javax.swing.GroupLayout(escritorioAdmin);
        escritorioAdmin.setLayout(escritorioAdminLayout);
        escritorioAdminLayout.setHorizontalGroup(
            escritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        escritorioAdminLayout.setVerticalGroup(
            escritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        archivoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/home.png")));
        archivoAdmin.setText("Archivo");
        menuAdmin.add(archivoAdmin);

        verAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/table.png")));
        verAdmin.setText("Ver");

        asignacionesAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clipboard.png")));
        asignacionesAdmin.setText("Asignaciones");
        verAdmin.add(asignacionesAdmin);

        eventosAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calendar.png")));
        eventosAdmin.setText("Eventos");
        verAdmin.add(eventosAdmin);

        calificacionesAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3d bar chart.png")));
        calificacionesAdmin.setText("Calificaciones");
        verAdmin.add(calificacionesAdmin);

        menuAdmin.add(verAdmin);

        mensajesAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mail.png")));
        mensajesAdmin.setText("Mensajes");
        menuAdmin.add(mensajesAdmin);

        busquedaAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search.png")));
        busquedaAdmin.setText("Busqueda");
        menuAdmin.add(busquedaAdmin);

        perfilAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/user group.png")));
        perfilAdmin.setText("Perfil");
        menuAdmin.add(perfilAdmin);

        alertasAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/warning.png")));
        alertasAdmin.setText("Alertas");
        menuAdmin.add(alertasAdmin);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscritorioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscritorioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscritorioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscritorioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscritorioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alertasAdmin;
    private javax.swing.JMenu archivoAdmin;
    private javax.swing.JMenuItem asignacionesAdmin;
    private javax.swing.JMenu busquedaAdmin;
    private javax.swing.JMenuItem calificacionesAdmin;
    private javax.swing.JDesktopPane escritorioAdmin;
    private javax.swing.JMenuItem eventosAdmin;
    private javax.swing.JMenu mensajesAdmin;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu perfilAdmin;
    private javax.swing.JMenu verAdmin;
    // End of variables declaration//GEN-END:variables
}
